title: Who am I?
author: Shamil Keheliya
email: shamilkeheliya@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I'm undergraduate software developer.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
